### ISSUE TITLE
error with prompt_cache

### ISSUE THREAD

**Issue by seocamo** [nvim-telescope/telescope-fzf-native.nvim#1]
i added this instand of the fzy plugin and run the find_file and got this error
Error executing vim.schedule lua callback: ...escope-fzf-native.nvim/lua/telescope/_extensions/fzf.lua:26: attempt to index field 'prompt_cache' (a nil value)
Error executing vim.schedule lua callback: ...escope-fzf-native.nvim/lua/telescope/_extensions/fzf.lua:26: attempt to index field 'prompt_cache' (a nil value)
Press ENTER or type command to continue

**Comment by Conni2461** [comment]
requires up to date telescope. forgot to mention that :laughing:

**Comment by seocamo** [comment]
i forgot to update telescope duh
