### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [nvim-telescope/telescope-fzf-native.nvim#108]
```
    ● telescope-fzf-native.nvim 0.06ms ✔  build
        mkdir -p build
        cc -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.so
        make: cc: No such file or directory
        make: *** [Makefile:24: build/libfzf.so] Error 127
```

My package manager is Lazy and this is the error I got.

**Comment by delphinus** [comment]
```
make: cc: No such file or directory
```

This mean your box has no binary: `cc`. You should install it before using this plugin. The way to install `cc` differs by OS you are using.

**Comment by AlphabetsAlphabets** [comment]
I see. I didn't know There's a binary called `cc`. I'll look for it, thanks.

**Comment by Conni2461** [comment]
`cc` isn't a binary on most systems, its a symlink to `gcc` or `clang` depending on your system. which os do you use? and is that still an issue?

**Comment by AlphabetsAlphabets** [comment]
> `cc` isn't a binary on most systems, its a symlink to `gcc` or `clang` depending on your system. which os do you use? and is that still an issue?

Apologies. I completely forgot about this, yes installing `cc` fixes it. I'm on Fedora and had to install it separately, unfortunately I do not remember the exact command.
