### ISSUE TITLE
Segfault when searching for branch with Polish characters

### ISSUE THREAD

**Issue by 3nuc** [nvim-telescope/telescope-fzf-native.nvim#11]
Repro:
```sh
git clone https://github.com/nvim-telescope/telescope-fzf-native.nvim
git checkout -b feature/PoprawićPaginacjeWPłatnościach #create the branch that will make fzf segfault when searched for
nvim
:Telescope git_branches
feature/PoprawićPaginacjeWPłatnościach #you can either paste or write this in the Telescope input box - it's easeier to paste
```

It segfaults on the second special character - the 'ł" in "Płatnościach" if you write it by hand
![nETkJe076l](https://user-images.githubusercontent.com/5359825/117773942-75d10280-b228-11eb-94cf-15250495523d.gif)

Commenting out `require('telesccope').load_extension('fzf')` in my config fixes the issue.

My telescope config: https://github.com/3nuc/dotfiles/blob/master/.config/nvim/lua/3nuc/plugins.lua#L39,L56

**Comment by 3nuc** [comment]
Looks like it happens for hyphens also:

```sh
git checkout -b feature/1337-some-times-branches-have-lots-of-hyphens
:Telescope git_branches
#try to re-type the full branch name
```

![0JgOGLcv3z](https://user-images.githubusercontent.com/5359825/117774511-1fb08f00-b229-11eb-847f-70dbf9017c69.gif)

**Comment by Conni2461** [comment]
Thanks for reporting.

I will look into it but i am currently also reworking how utf8 characters work. https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/10 (i have more work done locally) so you can lowercase and normalize them. 

Example: I have a `Ö` somewhere and i want to be able to match it with `ö` (lowercase) and `o` (normalize).

fzf does both things and i am currently working to bring this feature to this fork as well :)
(normalize will be configurable, enable/disable)

**Comment by Conni2461** [comment]
It was not a unicode issue. I hope i fixed it. Thanks for the detailed bug report :)

**Comment by 3nuc** [comment]
Just remembered I need to update nvim plugins after I segfaulted again.

The segfault doesn't happen anymore after I downloaded the newest version with your fix. Thanks!
