### ISSUE TITLE
When a search has been deleted or edited, the location of the picker doesn't scroll back to the top

### ISSUE THREAD

**Issue by sainttttt** [nvim-telescope/telescope-fzf-native.nvim#111]
If you search for a file and scroll down a few entries in the picker, and then delete the search query and enter something else, the cursor remains at the scrolled location instead of resetting to the top. It really should reset back to the top, as other pickers like telescope does this.

**Comment by sainttttt** [comment]
I figured out this is something to do with fzf itself, and can be fixed by the option `--bind change:top`

**Comment by ebkalderon** [comment]
I've been looking for a fix for this for a while, and I happened to stumble upon this ticket by chance. Where in the configuration exactly did you apply `--bind change:top`? Or is this option not possible to apply with `telescope-fzf-native.nvim`, being a native C implementation of `fzf`?
