### ISSUE TITLE
Symlinks does not show up in results

### ISSUE THREAD

**Issue by fiskfisk33** [nvim-telescope/telescope-fzf-native.nvim#113]
I can't find any way to get symlinks to show up in results, I'm probably missing something?

**Comment by FedeAbella** [comment]
This would be really helpful. Maybe some way to pass flags to the `fzf` command? That would make it so `--follow` can be passed

**Comment by FedeAbella** [comment]
Well, nvm. I kept searching and apparently this can be solved easily directly from Telescope.

@fiskfisk33 you can just call `:Telescope find_files follow=true` and symlinks will appear
