### ISSUE TITLE
Problem in cmake building script, causing "'fzf' extension doesn't exist or isn't ins talled"

### ISSUE THREAD

**Issue by ye-junzhe** [nvim-telescope/telescope-fzf-native.nvim#115]
## I have encountered a problem with building this plugin using the default cmake build script(lazy.nvim)

```lua
{ 'nvim-telescope/telescope-fzf-native.nvim', build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }
```

![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/53103747/81275a65-a7ce-42e8-a9ea-330793a0da64)

## Which leads to a problem that this line below won't work

`telescope.load_extension("fzf")`

![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/53103747/92c77889-9b56-4e9e-8ba4-a23d84cc920a)

## But fixed it after I change the last bit of the script to be `cd build && make`
```lua
{ 'nvim-telescope/telescope-fzf-native.nvim', build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cd build && make' },
```

![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/53103747/7b2f62ef-fc37-4b21-b0de-674cd0f56bc1)

## Env
- Debian 12
- Nvim 0.9.4

**Comment by Conni2461** [comment]
yeah the last install step is not needed, at least on linux, i dont know if its needed on windows :thinking: 

the person who wrote the docs was writing it with that in mind
