### ISSUE TITLE
Failed to run 'conifig' for telescope.nvim "fzf" extension is not installed: ....nvim [Windows](11)

### ISSUE THREAD

**Issue by SaiNikhil1258** [nvim-telescope/telescope-fzf-native.nvim#128]
Failed to run `config`for telescope.nvim                                                                                                                                            
...a/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ...nvim-data/lazy/teles            
cope-fzf-native.nvim/lua/fzf_lib.lua:11: cannot load module 'C:/Users/LENOVO/AppData/Local/nvim-data/lazy/telescope-fzf-native.nvim/lua/.            
./build/libfzf.dll': %1 is not a valid Win32 application.^M                                                                                                                                                                                                 
`
stacktrace:                                                                           - telescope.nvim\lua\telescope\_extensions\init.lua:10 _in_ **load_extension**                                         - telescope.nvim\lua\telescope\_extensions\init.lua:62 _in_ **load_extension**                                         - lua/plugins/telescope.lua:57 _in_ **config**   
`

`my code`
~~~
 extensions = {
     fzf = {
        fuzzy = true,                    -- false will only do exact matching
        override_generic_sorter = true,  -- override the generic sorter
        override_file_sorter = true,     -- override the file sorter
        case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
                                         -- the default case_mode is "smart_case"
      }
    }

  })
  require('telescope').load_extension('fzf')
~~~

when i add the extension `telescope-fzf-native.nvim` make is not able to find the config files and getting this issue when i remove this extension then `telescope` does work fine with all of its functionality
![Screenshot 2024-05-26 171830](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/111006116/b9a5fb4c-d454-490e-b353-3ada69fa0ee0)

* when i skip this error i am able to use telescope as usual it works fine not able to add `fzf`

**Comment by venom-10** [comment]
did you fixed that?

**Comment by SaiNikhil1258** [comment]
No

**Comment by a-roy** [comment]
I got it working by changing the lazy.nvim plugin spec to:
```lua
{
  "nvim-telescope/telescope-fzf-native.nvim",
  build = function(plugin)
    local obj = vim.system({"cmake", "-S.", "-Bbuild", "-DCMAKE_BUILD_TYPE=Release"}, {cwd = plugin.dir}):wait()
    if obj.code ~= 0 then error(obj.stderr) end
    obj = vim.system({"cmake", "--build", "build", "--config", "Release"}, {cwd = plugin.dir}):wait()
    if obj.code ~= 0 then error(obj.stderr) end
    obj = vim.system({"cmake", "--install", "build", "--prefix", "build"}, {cwd = plugin.dir}):wait()
    if obj.code ~= 0 then error(obj.stderr) end
  end
}
```
The suggested method of supplying the shell command just didn't seem to do anything.

**Comment by raphaelchristin** [comment]
uninstalling and reinstalling the plugin worked for me!

**Comment by linkliu** [comment]
if you follow the official default configuration, the cmake will build the "libfzf.dll" into the "build/Release" folder. then you should copy the libfzf.dll to the "build" root folder.
![微信截图_20240718105648](https://github.com/user-attachments/assets/e0dc3786-6679-426b-b056-5c8c1199048d)
![微信截图_20240718105725](https://github.com/user-attachments/assets/97900192-042d-4d30-b037-fb59b91e19fd)

**Comment by CalfMoon** [comment]
@linkliu is not completely wrong but he isn't right either. Accourding to the error given by @SaiNikhil1258 and me also getting the error, telescope expects .dll or .so file to be inside `telescope-fzf-native.nvim/lua/telescope/_extensions/build`. So i moved my build folder from and to as shown in screenshot.
![image](https://github.com/user-attachments/assets/d0a45963-bdde-4ffa-9d62-2379cf92736c)
![image](https://github.com/user-attachments/assets/380e18d0-48cc-497b-8e7e-9ad3cd2fdd10)
Also my build file was not inside build/Release, it was just inside build.

Also my plugin didn't start working when i reinstalled the plugin like @raphaelchristin alhough i also use nixos.
