### ISSUE TITLE
Poor search accuracy in comparison to fzf

### ISSUE THREAD

**Issue by carbolymer** [nvim-telescope/telescope-fzf-native.nvim#129]
The vim plugin has poor search accuracy in comparison to fzf. This has degraded in recent months for me.

This is a search result from `telescope-fzf-native.nvim`:
![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/228866/0ecfcb59-7bc0-4a4c-8ffe-9fbb68465d39)

This is from `fzf`:
![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/228866/ecb59d06-c045-409c-adb5-c7aa09ede83c)

There are 285 files in the directory and its subdirectories and `telescope-fzf-native.nvim` is unable to find the one I'm looking for.

I'm using default configuration from https://github.com/nvim-telescope/telescope-fzf-native.nvim#telescope-setup-and-configuration

Can I change something to improve search results in `telescope-fzf-native.nvim`? Can I use `fzf` in telescope instead?

Discussion on matrix: https://matrix.to/#/!cxlVvaAjYkBpQTKumW:gitter.im/$5a6gWdvJqzdkxRoKFEDVriawOiCg8J0j8oYyqoDL-uM?via=gitter.im&via=matrix.org&via=beeper.com

**Comment by Conni2461** [comment]
Hmm the first screenshot shows 12/257 found entries, but it seems like they arnt displayed. It appears that this is an telescope core issue that the scrollback of the buffer is somehow messed up and the results arent shown correctly or out of frame.

You could try a different theme or post a minimal reproduce config and then we can see if this is actually an issue with this plugin or with core.

We also havent actually change that much in the past two years. Especially in the past months

**Comment by carbolymer** [comment]
Wow good catch. Actually I can access the hidden entries with CTRL-N / CTRL-P. I'll raise an issue in telesope repo then.
