### ISSUE TITLE
Marking fuzzy=true has no effect

### ISSUE THREAD

**Issue by zlksnk** [nvim-telescope/telescope-fzf-native.nvim#18]
`fuzzy=true` doesn't brings back fuzzy behaviour of FZF.

**Config**

```lua
local telescope = require("telescope")

telescope.setup{
  defaults = {},
  extensions = {
    fzf = {
      fuzzy = true,
      override_generic_sorter = false,
      override_file_sorter = true,
      case_mode = "smart_case"
    }
  }
}

telescope.load_extension('fzf')
```

To reproduce, use `:Telescope find_files` with above config.

**Comment by Conni2461** [comment]
Sorry that was my bad. Just wanted to add more configuration :rofl: `fuzzy` should be default now and not be required to be set
