### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ashincoder** [nvim-telescope/telescope-fzf-native.nvim#28]
This shows an error when `make`
recording

[![asciicast](https://asciinema.org/a/UgsGvMoYCmHFpcWvFV7ArhKyO.svg)](https://asciinema.org/a/UgsGvMoYCmHFpcWvFV7ArhKyO)

**Comment by Conni2461** [comment]
Whats the error? It is printing the build command. And it looks successful to me

**Comment by ashincoder** [comment]
Is it not an error ok then
