### ISSUE TITLE
:Telescope fzf yields E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:184: attempt to call a nil value

### ISSUE THREAD

**Issue by elmarsto** [nvim-telescope/telescope-fzf-native.nvim#39]
After successful `:PackerSync` and restart, I still cannot run `:Telescope fzf`. I get the following error:

```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:184: attempt to call a nil value 
```

This is the relevant part of my config (packer-based, obvs)

```
    use {
      "nvim-telescope/telescope.nvim",
      requires = {
        "sharkdp/fd",
        "nvim-lua/plenary.nvim",
        {"nvim-telescope/telescope-packer.nvim", requires = "wbthomason/packer.nvim"},
        {"nvim-telescope/telescope-fzf-native.nvim", run = "make"}
      },
      config = function()
        local tscope = require("telescope")
        tscope.setup {}
        tscope.load_extension "packer"
        tscope.load_extension "fzf"
      end
    }

```

**Comment by elmarsto** [comment]
further contex
![20211009_18h06m47s_grim](https://user-images.githubusercontent.com/315987/136677695-2747acd6-434c-40ab-9788-a84383a22706.png)
t:

**Comment by fdschmidt93** [comment]
Completion for vim commands are auto-generated. Here, it's just that `telescope-fzf-native` is the odd one out across telescope extensions; for most other that would be meaningful as to consistently with built-in experience call the picker(s) of the extension as implemented [here](https://github.com/nvim-telescope/telescope.nvim/blob/ba41f0eeb13796c26f6c5f3e8c44b2397a466e39/plugin/telescope.vim#L88-L116) (eg `:Telescope frecency` for the popular [telescope-frecency](https://github.com/nvim-telescope/telescope-frecency.nvim)). Consequently, I'm afraid deactivating will be rather hard.

I realize landing on the `telescope-fzf-native` README lacking more telescope-context can be a bit confusing. Our [developers-guide](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md) is a great start to get more familiar with what and how telescope can do some of the things. 

> The sword, however, has a few sharp edges, and not always on the blade part ;D

Telescope can do much more; much more to the degree it's difficult to document and keep track of all of it :sweat_smile: 

> (If you're interested: Nix still generates the file named lattice_local.lua, which gets its fancy /nix/store/.../ absolute paths for binaries, which is kind of cool, but the built-in home-manager neovim config module just wasn't keeping up with Packer, and lengthened my edit/:PackerSync/debug cycle considerably, having to home-manager switch every time I tweaked it. (This is the one bad thing about nix: a change to any one file occasions a rebuild and, unless you're rocking a local copy of the nix channels, you are going to want to be Internet-connected.))

Nix would be my personal next step after Arch I suppose; maybe next time something breaks and I have some time getting into it :)
