### ISSUE TITLE
plugin has no effect

### ISSUE THREAD

**Issue by darzok0914** [nvim-telescope/telescope-fzf-native.nvim#45]
Hi, 

I'm using the latest telescope, with neovim 0.6.0 and I can't seem to be able to make this extension behave as I would expect. 

for example when I do a fzf BLines this the results I have:

![image](https://user-images.githubusercontent.com/72544332/144652613-853d8ffc-d4ff-4cfd-b19c-c67316c47aa6.png)

but when I do a Telescope current_buffer_fuzzy_find this what I have:

![image](https://user-images.githubusercontent.com/72544332/144652705-8f9b9264-8e95-4f69-98f5-c7e83d11148a.png)

same behaviour is observed between fzf GFiles and Telescope git_files

![image](https://user-images.githubusercontent.com/72544332/144653505-763953a4-a251-488a-bfb0-c4f327960a30.png)

I'm just getting started with lua world so it is possible I'm doing something really silly

**Comment by Conni2461** [comment]
Maybe not set the `*_sorter`s. the `pickers` is at the wrong place.
I cleaned it up for you but your config already works for me. So did you install it correctly? Did you ran `make`. Does neovim throw a bunch of errors if you open it?
```lua
local action_state = require "telescope.actions.state"
local actions = require "telescope.actions"
local telescope = require "telescope"

telescope.setup {
  defaults = {
    vimgrep_arguments = {
      "rg",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case",
      "--hidden",
    },
    color_devicons = true,
    sorting_strategy = "ascending",
    scroll_strategy = "limit",
    layout_config = {
      prompt_position = "top",
      height = 50,
      width = 180,
    },
    mappings = {
      i = {
        ["<C-j>"] = actions.move_selection_next,
        ["<C-k>"] = actions.move_selection_previous,
      },
    },
  },
  pickers = {
    current_buffer_fuzzy_find = {
      theme = "dropdown",
    },
  },
  extensions = {
    fzf = {
      fuzzy = true, -- false will only do exact matching
      override_generic_sorter = true,
      override_file_sorter = true,
      case_mode = "smart_case", -- this is default
    },
  },
}

require("telescope").load_extension "fzf"
require("telescope").load_extension "coc"
```

**Comment by darzok0914** [comment]
hi, thanks for your response, 

I just copy pasted your config and it's all working fine now. that's weird that my config was working for you. 

Thanks so much for your help, sorry it was a silly mistake from my config.
