### ISSUE TITLE
Fzf-native ignore file

### ISSUE THREAD

**Issue by Melkster** [nvim-telescope/telescope-fzf-native.nvim#49]
Is it possible for me to create an ignore file for fzf-native, kinda like how ripgrep has an `.rgignore`? Or should I be using `telescope.defaults.file_ignore_patterns`? Does fzf-native support that?

**Comment by Conni2461** [comment]
No use `file_ignore_patterns` i dont think its fits in the scope of telescope-fzf-native.
You can still obviously remove items based on a pattern dynamically with `!pattern`. Like described in the readme

**Comment by Melkster** [comment]
Isn't ignoring a set of file patterns crucial to a fuzzy finder though? Both to avoid parsing huge unwanted directories like `node_modules/`, but also to ignore files that one would never want to open in Neovim, for instance `.bin` files?

**Comment by Conni2461** [comment]
Yeah sure i agree. But this repo is not a fuzzy finder. Its an implementation of an algorithm as library so telescope can use it. You should use `telescope.defaults.file_ignore_patterns`. I dont understand why i should re implement it. Do you want to specify ignore patterns fuzzy with this algorithm?

**Comment by Melkster** [comment]
Oh I see, I misunderstood your earlier comment because it sounded to me like `file_ignore_patterns` didn't work for fzf-native. That's my bad. I'll use that then!
