### ISSUE TITLE
allocate_slab (nil value)

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope-fzf-native.nvim#5]
Good day to you!

I've got an up to date plugin and telescope
I'm using default packer installation and default setup and config

Running any command with fzf-native showing me this error:

![image](https://user-images.githubusercontent.com/52028706/115916233-f56f7b00-a48d-11eb-9cab-c9d32afb0d94.png)

**Comment by Conni2461** [comment]
whats the output of `:lua print(vim.inspect(require("fzf")))`

**Comment by Conni2461** [comment]
Okay i opened your profile and after three click ran into https://github.com/vijaymarupudi/nvim-fzf which uses `fzf` as module name. I did not know about this plugin before that, so i probably should rename my base module into `fzf_native` or similar, to avoid this issue.

**Comment by tami5** [comment]
:D well fzf it's the right name for this plugin since it isn't a wrapper like nvim-fzf :D just saying. maybe nvim-fzf and fzf-native shouldn't be installed together

**Comment by fedoranvar** [comment]
> :lua print(vim.inspect(require("fzf")))

{
  default_window_options = {},
  fzf = <function 1>,
  fzf_relative = <function 2>,
  provided_win_fzf = <function 3>,
  raw_fzf = <function 4>
}



> Okay i opened your profile and after three click ran into https://github.com/vijaymarupudi/nvim-fzf which uses `fzf` as module name. I did not know about this plugin before that, so i probably should rename my base module into `fzf_native` or similar, to avoid this issue.

yup, removed nvim-fzf and now it's all working

Thank you!

**Comment by Conni2461** [comment]
I need to think about this
