### ISSUE TITLE
Not working for live_grep

### ISSUE THREAD

**Issue by ledesmablt** [nvim-telescope/telescope-fzf-native.nvim#53]
Works completely fine for some commands like `find_files` but not `live_grep` (which I rely on the most).

Link to my telescope config [here](https://github.com/ledesmablt/dotfiles/blob/8d9355aff1ff3f6682421776dfa7b7cfa0fd1bcf/config/nvim/lua/config/telescope.lua)

Proof:

Working for find_files (space is respected)
![image](https://user-images.githubusercontent.com/22242264/149815777-688ada59-4797-45a3-80fd-ac70839ab200.png)

Not working for live_grep (space not respected)
![image](https://user-images.githubusercontent.com/22242264/149815889-03189670-8e9b-47c6-b046-6ff0ec6728a4.png)

FZF :Rg behavior (desired, space is respected)
![image](https://user-images.githubusercontent.com/22242264/149815931-584898ab-7b36-407a-9bbc-8eab000b06d9.png)

**Comment by Conni2461** [comment]
Telescope doesnt use sorters for `live_grep`.

You can do `Telescope grep_string search=`. Fuzzy live grep needs to be fixed in telescope core not here. We have it on our roadmap https://github.com/nvim-telescope/telescope.nvim/projects/2 https://github.com/nvim-telescope/telescope.nvim/issues/564

**Comment by ledesmablt** [comment]
Appreciate the response, thanks!

**Comment by ssh352** [comment]
because of this limitation, I still use fzf for string search.

**Comment by dylan-chong** [comment]
I use `grep_string` instead of `live_grep` and this plugin works
