### ISSUE TITLE
`Plug` uses branch 'master' but it's missing files including `Make`

### ISSUE THREAD

**Issue by dlaub3** [nvim-telescope/telescope-fzf-native.nvim#66]
I don't see a branch named 'master' for this repo, only 'main'. So I'm not sure how Plug is able to checkout a branch named 'master'. But however it works it only has a few files/folders. 

- LICENSE
- README
- lua
- deps

I attempted to use `Plug 'nvim-telescope/telescope-fzy-native.nvim', { 'branch': 'main', 'do': 'make' }`. But this still resulted in checking out the same branch as before.

As I don't understand how `Plug` works it's possible that this is a problem with `Plug`.

**Comment by dlaub3** [comment]
`git log` shows only one commit `7b3d2528102f858036627a68821ccf5fc1d78ce4`.

**Comment by Conni2461** [comment]
`fzf` not `fzy`.

Just copy and past it from the readme. `Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }` plug can checkout man branches.
