### ISSUE TITLE
Strange and random segmentation faults

### ISSUE THREAD

**Issue by epixinvites** [nvim-telescope/telescope-fzf-native.nvim#67]
Here's the backlog -> https://termbin.com/ml6x

**Comment by Conni2461** [comment]
when did these segfaults happen? Are you using telescope at the time?

I only see `fzf-native` listed as `Module` not nowhere in the stacktrace, Any chance you can build neovim in `debug` or in `RelWithDebInfo`?

**Comment by epixinvites** [comment]
These segfaults happen at random times, but it only happens when I continuously press <Down>, <Up>, <Left> or <Right>. Out of 50 times I do that around once it will crash

**Comment by Conni2461** [comment]
cant reproduce.

I dont think this is a fzf-native issue? I need a stacktrace with symbols, if you can produce one. Also a neovim version, etc

**Comment by epixinvites** [comment]
Crashes disappeared after unplugging telescope-fzf-native.nvim, seems like it had compatibility issues with some other plugin I had.

**Comment by Conni2461** [comment]
also make sure you have a up to date build. You can just run `make clean && make` in the project dir.

I wont comment anymore until i have a coredump with symbols. Otherwise i dont have enough information

**Comment by epixinvites** [comment]
alright, i'll try to catch the segfault again

**Comment by Conni2461** [comment]
any luck?

**Comment by epixinvites** [comment]
Can't reproduce it again, I updated all my plugins, luajit and neovim and it just went away.

**Comment by Conni2461** [comment]
:laughing: I'll close this issue for now. If you see it again with more information, feel free to reopen :)
