### ISSUE TITLE
!bang matching shows no results when the ! match is the only string to match

### ISSUE THREAD

**Issue by rmagatti** [nvim-telescope/telescope-fzf-native.nvim#7]
## Description
So I know the readme mentions there won't necessarily be 1:1 feature parity with fzf, but I did notice something strange when using fzf-native that's quite different than fzf that I'm not sure is the intended behaviour.

When starting the match with a !bang exclusion pattern, in fzf results still show up, respecting the exclusion match, with fzf-native they don't.

### Correct exclusion when !bang pattern is not the first pattern to match
![2021-04-24 22 54 42](https://user-images.githubusercontent.com/2881382/115981403-ae968980-a550-11eb-914c-253c40389e66.gif)

### Example of no results showing when the !bang match is the first match, but appearing when extra matching is provided.
![2021-04-24 22 55 36](https://user-images.githubusercontent.com/2881382/115981430-f0273480-a550-11eb-8b5d-21dcf39279c6.gif)

### Fzf/expected behaviour
![2021-04-24 22 56 06](https://user-images.githubusercontent.com/2881382/115981448-1b118880-a551-11eb-9d50-cde956e3b4a2.gif)

**Comment by Conni2461** [comment]
yep good catch. Will address that next week. Thanks for reporting :)

**Comment by Conni2461** [comment]
This should be implemented in the last commit. Feel free to reopen if it doesn't work as expected (and feel free to open new issues if you find more oddness. I know its not perfect yet :rofl:).

Thanks for reporting :)
