### ISSUE TITLE
Error executing Lua callback | libfzf.dll was built

### ISSUE THREAD

**Issue by markguzzo** [nvim-telescope/telescope-fzf-native.nvim#70]
Hello,
my first github issue, not too sure where to file this.

I followed the steps and installed the latest build that supports Windows and I've checked and indeed the dll is created in "\Local\nvim-data\site\pack\packer\start\telescope-fzf-native.nvim\build\libfzf.dll". When I relaunch nvim (version 0.7) I still get the following error:

`
Error executing Lua callback: ...ck\packer\start\telescope.nvim/lua/telescope/command.lua:193: attempt to call a nil value
stack traceback:
	...ck\packer\start\telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
	...ck\packer\start\telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
	...te\pack\packer\start\telescope.nvim\plugin\telescope.lua:109: in function <...te\pack\packer\start\telescope.nvim\plugin\telescope.lua:108>
`

If this is not the place to ask, thats cool.. just tell me to go pound sand. 

I did my best trying to look at the error and look at the calls provided by the error msg, but I just don't know Lua (at all) and nothing really jumped out at me. So it's not the fact that the dll isn't being created, because it is... 

really wanted to try this plugin/addon

**Comment by markguzzo** [comment]
Well then.. I didn't realize that fact. 

Yes.. I get that error when calling `:Telescope fzf` 

I thought that was the way due to `fzf` showing up as a picker in the `:Telescope ` list.

Thanks for being helpful.

**Comment by Conni2461** [comment]
To fix this, we need to rewrite the extension interface in telescope. Closing in favor of https://github.com/nvim-telescope/telescope.nvim/issues/2146
