### ISSUE TITLE
packer.nvim: ... 'fzf' extension doesn 't exist or isn't installed: ..... local/share/nvim/site/pack/packer/start/telescope -fzf-native.nvim/build/libfzf.so' (no such file)

### ISSUE THREAD

**Issue by chomosuke** [nvim-telescope/telescope-fzf-native.nvim#74]
Hi, thank you for making this awesome plugin.

I have been trying to install fzf and get it working for a while now. However, it doesn't seems to work. 

I've produced a minimum config that reproduce the issue, here's a screenshot of me trying to run PackerSync right after I added telescope & telescope-fzf-native
![Screen Shot 2022-06-09 at 10 31 00 pm](https://user-images.githubusercontent.com/38484873/172849987-fdd9f89e-14c3-4f4c-b070-3150725676b8.png)

Here's my config in case you want to copy it
```
return require 'packer'.startup(function()
  -- for packer to host itself
  use 'wbthomason/packer.nvim'

  -- for telescope finding files
  use {
    'nvim-telescope/telescope-fzf-native.nvim',
    run = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build',
  }
  use {
    'nvim-telescope/telescope.nvim',
    config = function()
      require 'telescope'.setup {}
      require 'telescope'.load_extension 'fzf'
    end,
    requires = 'nvim-lua/plenary.nvim',
  }
end)
```

I tried to run the cmake command in the plugin's directory, everything seems to be fine:
![Screen Shot 2022-06-09 at 10 31 03 pm](https://user-images.githubusercontent.com/38484873/172849260-da61a975-f3a1-413d-88bd-91e6174e81f4.png)

I am on macOS 12.4

May I ask what am I doing wrong? Any help is greatly appreciated.

Thanks

**Comment by Conni2461** [comment]
I just merged a PR https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/73 that might address your issue. Can you repull and try again?

The cmake version is pretty new and it seems that it wasn't working for macos. I hope that is fixed now. Otherwise  setting 
`run = 'make',` is still supported
