### ISSUE TITLE
make option in Windows failed because of wrong MKD command

### ISSUE THREAD

**Issue by Guoan-Tang** [nvim-telescope/telescope-fzf-native.nvim#80]

**Comment by Guoan-Tang** [comment]
I add `use {'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }` into plugins.lua and run `PackerSync`, got an error:

![image](https://user-images.githubusercontent.com/66197601/183798897-922e89aa-bb9c-42f6-b858-703811ced81c.png)

To figure out the details, I run `make` in the repo directly, and got:

`mkdir build
process_begin: CreateProcess(NULL, mkdir build, ...) failed.
make (e=2): The system cannot find the file specified.
make: [build/libfzf.dll] Error 2 (ignored)
gcc -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.dll
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file build/libfzf.dll: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [build/libfzf.dll] Error 1`

which is cause by the wrong MKD command for windows: [-mkdir](https://github.com/nvim-telescope/telescope-fzf-native.nvim/blob/6a33ecefa9b3d9ade654f9a7a6396a00c3758ca6/Makefile)

And it was fixe when I replace it to `cmd /C mkdir`

**Comment by Conni2461** [comment]
resolved with #81
