### ISSUE TITLE
[BUG] `make` enters interactive cmd.exe on Windows with MSYS2

### ISSUE THREAD

**Issue by mediumrarez** [nvim-telescope/telescope-fzf-native.nvim#82]
On Windows with MSYS2, running `make` hangs because `cmd /c` enters `cmd.exe` interactive mode. (Also the command `cmd /c` was supposed to run doesn't run.)

![Animation](https://user-images.githubusercontent.com/59168253/187295434-477ec9ad-b9c8-4b07-a241-77c1c0491c5f.gif)

The offending line in `Makefile` is this: `ifeq ($(OS),Windows_NT)`. It needs to match Windows while excluding MSYS2.

According to https://stackoverflow.com/a/52062069 we can do this by looking for instances of `;` in `PATH`:

```Makefile
ifeq '$(findstring ;,$(PATH))' ';'
    # is normal windows
else
    # is linux or linux-like (e.g. MSYS2) environment
endif
```

**Comment by Conni2461** [comment]
does https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/87 help?

**Comment by mediumrarez** [comment]
@Conni2461 Yes, #87 fixes the bug.
