### ISSUE TITLE
How do I know if this is working correctly.

### ISSUE THREAD

**Issue by ariel-frischer** [nvim-telescope/telescope-fzf-native.nvim#83]
:checkhealth Telescope doesn't say much except:
```
## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```
My telescope config is searching fine but I can't tell if fzf-native is being used in background.

**Comment by Conni2461** [comment]
Yeah i haven't added a healthcheck yet. I will do that. Thanks for reminding me

You can check if you can do a query like: `!.md test` this should filter out all markdown files, with a second query `test`

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/84 implements a health check

**Comment by ehaynes99** [comment]
FWIW, this is working perfectly for me:
```
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.5.3

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured
```

**Comment by Conni2461** [comment]
fixed in https://github.com/nvim-telescope/telescope-fzf-native.nvim/commit/8fff2b20b2eb788b76015639352eb8ebbec87cd9
