### ISSUE TITLE
Can't check is it working

### ISSUE THREAD

**Issue by lumpsoid** [nvim-telescope/telescope-fzf-native.nvim#86]
I am confused by the way the sorter works
this is my custom picker:
![screenshot_20221019105036](https://user-images.githubusercontent.com/79290581/196635357-c8ba5280-844a-470e-ba52-67812ba3949d.jpeg)

when I use original fzf plugin for vim I see this:
![screenshot_20221019104850](https://user-images.githubusercontent.com/79290581/196635447-a12887bb-a40a-4152-90a1-91c488ee23ed.jpeg)

but when I try to use my custom picker in same search I see that result:
![screenshot_20221019104924](https://user-images.githubusercontent.com/79290581/196635581-f75cb5b6-f76d-4a86-a4c2-320e0b90e868.jpeg)

and also this result is weird:
![screenshot_20221019105001](https://user-images.githubusercontent.com/79290581/196635682-e76becb7-e5f2-4eb2-89ca-192fc47f6c9d.jpeg)
![screenshot_20221019105007](https://user-images.githubusercontent.com/79290581/196635698-d60c9064-4093-4267-9ca2-a4dee25be389.jpeg)

and I can't checkhealth, but I saw that you implement this
![screenshot_20221019104938](https://user-images.githubusercontent.com/79290581/196635802-405b88af-2918-4001-bf2e-83214e37e7f8.jpeg)
in my .config/nvim/plugin/telescope-setup.lua
I have that configuration
```lua
-- You dont need to set any of these options. These are the default ones. Only
-- the loading is important
require('telescope').setup {
  extensions = {
    fzf = {
      fuzzy = true,                    -- false will only do exact matching
      override_generic_sorter = true,  -- override the generic sorter
      override_file_sorter = true,     -- override the file sorter
      case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
                                       -- the default case_mode is "smart_case"
    }
  }
}
-- To get fzf loaded and working with telescope, you need to call
-- load_extension, somewhere after setup function:
require('telescope').load_extension('fzf')
```

and this code in packer plugin:
```lua
use {'nvim-telescope/telescope-fzf-native.nvim', run = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by lumpsoid** [comment]
but for `:Telescope oldfiles` fuzzy search works

**Comment by lumpsoid** [comment]
okey, this is a problem with `live_grep` picker
this picker is not compatible with this sorter

**Comment by lumpsoid** [comment]
and I find, how it's working – https://github.com/nvim-telescope/telescope.nvim/issues/564#issuecomment-786850776
and how you can make workaround with `grep_string` picker

**Comment by Conni2461** [comment]
Its not an issue, its intended behavior of live grep where each prompt goes directly to ripgrep, giving you regex support and more.

We maybe can document this better whatever this is

> Search for a string and get results live as you type, respects .gitignore

Also also the "workaround" is exactly what the `:Rg` implementation does

But hey if you wanna help me improve the getting started with this plugin, i would greatly appreciate anyone testing this PR https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/84
It should then give feedback if everything works by running `checkhealth telescope`

**Comment by lumpsoid** [comment]
basically, I need to checkout to this branch and run the code, and write a feedback, right?

**Comment by Conni2461** [comment]
Yeah, checkout this branch, and run `:checkhealth telescope` it should then give feedback in the `fzf-native` section if all checks passed.

Thanks would really appreciate anyone testing this new feature :)
