### ISSUE TITLE
how to ignore files? completely lost in FZF_DEFAULT_COMMAND etc

### ISSUE THREAD

**Issue by emilBeBri** [nvim-telescope/telescope-fzf-native.nvim#95]
sorry, I just have no idea how to make it exclude files and folders. I tried setting the FZF_DEFAULT_COMMAND in .bashrc, but that did nothing.

**Comment by linrongbin16** [comment]
You should customize `find_command` in find_files

**Comment by dylan-chong** [comment]
did you find out how to do it @emilBeBri

**Comment by emilBeBri** [comment]
I did, thank you.
